'use client';
import Image from 'next/image';
import {AnimatePresence, LayoutGroup, motion, useReducedMotion, useScroll, useSpring, useTransform} from 'framer-motion';
import {useEffect, useState} from 'react';
import {content, screenshotUrl} from '../data/content';
import {Icon, ImageWithFallback, PageLoader, Reveal} from './components';

function Header(){const [scrolled,setScrolled]=useState(false);const [open,setOpen]=useState(false);const [active,setActive]=useState('home');const {scrollYProgress}=useScroll();const scaleX=useSpring(scrollYProgress,{stiffness:100,damping:30});useEffect(()=>{const on=()=>setScrolled(window.scrollY>20);window.addEventListener('scroll',on);const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:'-35% 0px -55%'});content.nav.forEach(n=>{const el=document.querySelector(n.href);if(el)obs.observe(el)});return()=>{window.removeEventListener('scroll',on);obs.disconnect()}},[]);return <><motion.div className="progress" style={{scaleX}}/><header className={scrolled?'scrolled':''}><a className="brand" href="#home"><span>MH</span><b>Manahil Hassan</b></a><nav>{content.nav.map(n=><a key={n.href} className={active===n.href.slice(1)?'active':''} href={n.href}>{n.label}</a>)}<a className="button button-small" href="#contact">Let's Talk</a></nav><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-label={open?'Close menu':'Open menu'}><Icon name={open?'close':'menu'}/></button></header><AnimatePresence>{open&&<motion.div className="mobile-menu" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}>{content.nav.map(n=><a key={n.href} href={n.href} onClick={()=>setOpen(false)}>{n.label}</a>)}<a className="button" href="#contact" onClick={()=>setOpen(false)}>Let's Talk</a></motion.div>}</AnimatePresence></>}

function SectionTitle({number,title,intro}){return <div className="section-heading"><span className="section-number">{number}</span><div><h2>{title}</h2>{intro&&<p>{intro}</p>}</div></div>}
function Hero(){const reduce=useReducedMotion();const {scrollY}=useScroll();const y=useTransform(scrollY,[0,600],[0,reduce?0:70]);return <section id="home" className="hero wrap"><div className="hero-copy"><div className="eyebrow">Web · WordPress · SEO · Design</div><motion.h1 initial={reduce?false:{opacity:0,y:38}} animate={reduce?{}:{opacity:1,y:0}} transition={{duration:.7,delay:.15}}>Manahil <em>Hassan</em></motion.h1><motion.p className="hero-sub" initial={reduce?false:{opacity:0,y:24}} animate={reduce?{}:{opacity:1,y:0}} transition={{duration:.7,delay:.28}}>{content.title}</motion.p><motion.p className="hero-text" initial={reduce?false:{opacity:0,y:24}} animate={reduce?{}:{opacity:1,y:0}} transition={{duration:.7,delay:.4}}>I build websites, improve online visibility, and create digital experiences that are clean, practical, and easy to use — across web development, WordPress, SEO, and design.</motion.p><motion.div className="hero-actions" initial={reduce?false:{opacity:0}} animate={reduce?{}:{opacity:1}} transition={{delay:.55}}><a className="button" href="#work">View My Work <Icon name="arrow"/></a><a className="button button-outline" href="#contact">Let's Work Together</a></motion.div><div className="facts">{content.facts.map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span></div>)}</div></div><motion.div className="hero-portrait" style={{y}}><div className="portrait-frame"><Image src={content.portrait} alt="Portrait of Manahil Hassan" fill priority onLoad={(e)=>e.currentTarget.classList.add('loaded')}/></div><div className="portrait-label">Independent creative partner <span>—</span> Pakistan</div></motion.div></section>}
function About(){return <section id="about" className="section about"><div className="wrap"><SectionTitle number="01" title="A bit about how I work"/><div className="about-grid"><div className="about-intro">A practical, connected approach to digital work.</div><div className="about-copy">{content.about.map(p=><p key={p}>{p}</p>)}<div className="tags">{content.aboutTags.map(t=><span key={t}>{t}</span>)}</div></div></div></div></section>}
function ProjectCard({project,featured=false}){return <motion.article layout className={featured?'project-featured':'project-card'} whileHover={{y:-5}} transition={{duration:.2}}><a href={project.url} target="_blank" rel="noopener noreferrer" className="project-link"><ImageWithFallback project={project} featured={featured}/><div className="project-meta"><div><span className="category">{project.category}</span><h3>{project.title}</h3></div><span className="visit">Visit Website <Icon name="arrow"/></span></div><p className="role">{project.role}</p><p>{project.description}</p>{project.tags&&<div className="project-tags">{project.tags.map(t=><span key={t}>{t}</span>)}</div>}</a></motion.article>}
function Work(){const [filter,setFilter]=useState('All');const cats=['All','Web Development','WordPress','SEO','Website Management'];const visible=content.projects.filter(p=>filter==='All'||(p.filters||[p.category]).includes(filter));const featured=content.projects[0];return <section id="work" className="section work"><div className="wrap"><SectionTitle number="02" title="Projects I've contributed to" intro="A mix of websites I've built and sites I manage or support with ongoing SEO and content work."/><Reveal><ProjectCard project={featured} featured/></Reveal><div className="filter-row"><span>Filter by</span><LayoutGroup>{cats.map(c=><button key={c} className={filter===c?'selected':''} onClick={()=>setFilter(c)}>{c}{filter===c&&<motion.i layoutId="filter-line"/>}</button>)}</LayoutGroup></div><motion.div className="project-grid" layout><AnimatePresence mode="popLayout">{visible.map(p=><ProjectCard project={p} key={p.title}/>)}</AnimatePresence></motion.div><div className="timeline"><h3>Where I've contributed</h3>{content.timeline.map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span></div>)}</div></div></section>}
function Services(){return <section id="services" className="section services"><div className="wrap"><SectionTitle number="03" title="What I can help with"/><div className="service-list">{content.services.map(([a,b],i)=><Reveal key={a} delay={i*.04}><div className="service-item"><span>0{i+1}</span><h3>{a}</h3><p>{b}</p><Icon name="arrow"/></div></Reveal>)}</div></div></section>}
function Skills(){return <section id="skills" className="section skills"><div className="wrap split-heading"><SectionTitle number="04" title="Skills & toolkit"/><div className="skills-list">{Object.entries(content.skills).map(([a,items])=><div key={a}><h3>{a}</h3><div className="tags">{items.map(x=><span key={x}>{x}</span>)}</div></div>)}</div></div></section>}
function Process(){return <section id="process" className="section process"><div className="wrap"><SectionTitle number="05" title="How a project comes together"/><div className="process-grid">{content.process.map(([a,b],i)=><Reveal key={a} delay={i*.08}><div><span className="process-no">0{i+1}</span><h3>{a}</h3><p>{b}</p></div></Reveal>)}</div></div></section>}
function Contact(){const [state,setState]=useState('idle');async function submit(e){e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));if(!data.name?.trim()||!data.email?.trim()||!data.message?.trim()){setState('error');return}setState('loading');try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error();form.reset();setState('success')}catch{setState('error')}}return <section id="contact" className="section contact"><div className="wrap contact-grid"><div><SectionTitle number="06" title="Let's talk about your project"/><p>Send a message with a bit about what you need — a new website, WordPress help, SEO work, or design — and I'll get back to you.</p><div className="contact-links"><a href={`mailto:${content.email}`}>{content.email}</a><a href={`tel:+923453193995`}>{content.phone}</a><a href={content.linkedin} target="_blank" rel="noopener noreferrer">Connect on LinkedIn <Icon name="arrow"/></a></div></div><form onSubmit={submit} noValidate><label>Name<input name="name" required /></label><label>Email<input name="email" type="email" required /></label><label>Message<textarea name="message" rows="5" required /></label><button className="button" disabled={state==='loading'}>{state==='loading'?'Sending…':'Send Message'} <Icon name="arrow"/></button><AnimatePresence mode="wait">{state==='success'&&<motion.p className="form-success" initial={{opacity:0,y:5}} animate={{opacity:1,y:0}}>Thanks — your message is on its way.</motion.p>}{state==='error'&&<motion.p className="form-error" initial={{opacity:0,y:5}} animate={{opacity:1,y:0}}>Please check the form and SMTP setup, then try again.</motion.p>}</AnimatePresence></form></div></section>}
function Cta(){return <section className="cta"><div className="wrap"><div><span>Have a project in mind?</span><h2>Let's build something useful.</h2></div><div className="cta-actions"><a className="button button-light" href="#contact">Start a Project</a><a className="button button-berry-outline" href="#work">View My Work</a></div></div></section>}
function Footer(){return <footer><div className="wrap footer-top"><div><strong>MANAHIL HASSAN</strong><p>{content.title}</p><small>Web Design · SEO · Digital Creative</small></div><div className="footer-links"><div><a href={content.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn</a><a href={`mailto:${content.email}`}>Email</a></div><div>{content.nav.map(n=><a key={n.href} href={n.href}>{n.label}</a>)}</div></div></div><div className="wrap footer-bottom">© 2026 Manahil Hassan. All rights reserved.</div></footer>}
export default function Page(){return <><PageLoader/><Header/><main><Hero/><About/><Work/><Services/><Skills/><Process/><Cta/><Contact/></main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Person",name:content.name,jobTitle:content.title,email:`mailto:${content.email}`,sameAs:[content.linkedin]})}}/></>}
